name: Merge conflict check
on:
  push:
    branches:
      - main
  pull_request_target:
      branches:
      - main
      types:
        - opened
        - synchronize
        - edited

jobs:
  main:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Check for dirty pull requests
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        
        with:
          dirtyLabel: 'status: conflict'
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          commentOnDirty: |
            This pull request has conflicts ☹
            Please resolve those so we can review the pull request.
            Thanks.

      - name: Check for outdated branch
        id: resolution
        uses: actions/checkout@v2
        with:
          run: |
            if [ $(git merge-base @ master) == $(git rev-parse master) ]
            then
              echo "Your branch is up to date."
              exit 0
            else
              echo "You need to merge / rebase."
              exit 1
            fi
          dirtyLabel: 'status: outdated'
          failWhenOutdated: false
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          commentOnDirty: |
            This pull request is outdated ☹
            Please update the branch with the latest changes.
            Thanks.

